caldavdir = "~/.local/share/vdirsyncer/caldav"
editor = "nvim"
email = "torgny.bjers@gmail.com"
gpgkey = "6AA80D1F9E75594A9C1BCFE215B53F48CECB02C4"
loginmanager = "true"
name = "Torgny Bjers"
shell = "zsh"
wm = "sway"
